table YD_05_01_main_without_conv
	lineageTag: 092e6c3a-023d-49af-a93a-3336e32b0980

	column id
		dataType: double
		lineageTag: 508f7cff-f408-41ca-9dc4-9b656abe4e55
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2d8406e2-1ecd-421a-b260-df1d05f01eb0
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column source_type_id
		dataType: double
		lineageTag: 9f9bd3cd-4ce9-47d4-9d66-83b6b74d709b
		summarizeBy: sum
		sourceColumn: source_type_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column account_id
		dataType: double
		lineageTag: 0b4ea36c-ca4b-4ad9-8939-5a46bf87f192
		summarizeBy: sum
		sourceColumn: account_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column campaign_id
		dataType: int64
		formatString: 0
		lineageTag: 4b5dd3a6-b207-4c42-a9f9-eda47db42d52
		summarizeBy: sum
		sourceColumn: campaign_id

		annotation SummarizationSetBy = Automatic

	column id_key_camp
		dataType: string
		lineageTag: 7778af18-0264-449d-bfa7-1da47e23cf19
		summarizeBy: none
		sourceColumn: id_key_camp

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 37bcd97d-6730-4dab-bc16-53cf70e47818
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column age
		dataType: string
		lineageTag: 1f392b71-03c7-407f-91a9-347b4fe6b282
		summarizeBy: none
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column device
		dataType: string
		lineageTag: e6e7f30c-3a12-4bb4-a05f-7d45fe3bd2a0
		summarizeBy: none
		sourceColumn: device

		annotation SummarizationSetBy = Automatic

	column sessions
		dataType: int64
		formatString: 0
		lineageTag: c9ed7cdf-fb2b-4806-9a44-00b187c1ab73
		summarizeBy: sum
		sourceColumn: sessions

		annotation SummarizationSetBy = Automatic

	column bounces
		dataType: int64
		formatString: 0
		lineageTag: cd8baafc-de70-461d-84bc-08f9774b4d38
		summarizeBy: sum
		sourceColumn: bounces

		annotation SummarizationSetBy = Automatic

	column impressions
		dataType: int64
		formatString: 0
		lineageTag: 0345ed4d-8912-4938-b26d-c186233f8d18
		summarizeBy: sum
		sourceColumn: impressions

		annotation SummarizationSetBy = Automatic

	column clicks
		dataType: int64
		formatString: 0
		lineageTag: cebaf07f-1ade-42de-a1ba-9b6fa0270a8c
		summarizeBy: sum
		sourceColumn: clicks

		annotation SummarizationSetBy = Automatic

	column costs_without_nds
		dataType: double
		lineageTag: 00995a4c-4827-4d9e-8e7e-9d591269b24d
		summarizeBy: sum
		sourceColumn: costs_without_nds

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column costs_nds
		dataType: double
		lineageTag: 0f6a44e8-518d-4585-b2e1-0b1bb4c5996c
		summarizeBy: sum
		sourceColumn: costs_nds

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition YD_05_01_main_without_conv = m
		mode: import
		queryGroup: 05_05_Пол_Возраст_Устройство
		source = ```
				let
				    Источник = MySQL.Database(server_addres&":"&server_port, db_name, [ReturnSingleDatabase=true, 
				    Query="select id, date, source_type_id, account_id, campaign_id, id_key_camp, 
				            gender, age, device,
				            sessions, bounces, impressions, clicks, 
				            costs_without_nds_ak as costs_without_nds, costs_nds_ak as costs_nds
				            from YD_05_01_main_without_conv", 
				    CommandTimeout=#duration(0, 0, 10, 0)]),
				    #"Измененный тип" = Table.TransformColumnTypes(Источник,{{"date", type date}})
				    
				in
				    #"Измененный тип"
				```

	annotation PBI_NavigationStepName = Навигация

	annotation PBI_ResultType = Table

